const mongoose = require("mongoose");

const newResponseSchema = new mongoose.Schema({
  date: String,
  uuid: String,
  name: String,
  company: String,
  title: String,
  email: String,
  phone: String,
  question1: Object,
  question2: Array,
  question2none: Boolean,
  question2dontknow: Boolean,
  question3: Object,
  question4: Array,
  question4other: String,
  question5: Object,
  question6: String,
  question7: String,
  question8: String,
  question9: String,
  question10A: Object,
  question10B: Object,
  question11: Object,
  question12: Object,
  question13: Object,
  question14: Object,
  question15: Object,
  question16: String,
  question17: Object,
  question18: Object,
  question19: {
    input: Array,
    none: Boolean,
    dontknow: Boolean,
    other: String,
  },
  question20: Object,
  question21: Object,
  question22: Object,
  question23: String,
  question24: Array,
  question24none: Object,
  question24not: Object,
  question25A: Array,
  question25Anone: Boolean,
  question25Adontknow: Boolean,
  question25Aother: String,
  question25B: Object,
  question25Bnone: Boolean,
  question25Bdontknow: Boolean,
  question25C: Array,
  question25Cnone: Boolean,
  question25Cdontknow: Boolean,
  question25Cother: String,
  question26: String,
  question27: String,
  question28: String,
  questionA: String,
  questionAother: String,
  questionB: String,
  questionC: String,
  questionCother: String,
  questionD: String,
  questionE: String,
  questionF: String,
  questionFother: String,
  questionG: String,
  questionH: String,
  questionI: String,
  questionJ: String,
});

const NewResponse = mongoose.model("NewResponse", newResponseSchema);

exports.NewResponse = NewResponse;
